from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDF
import csv
import validators
import sys
import json


# a main operation function
def convert_csv_to_turtle(filename) -> Graph:
    """
    Adds all informations as RDF triples from the input filename into a graph and return it.
    @Pre: input filename must be type string.
    @Post: Returns a RDF.Graph that has all the triples
    """

    if len(sys.argv) != 2:
        raise ValueError("Invalid number of input filename")

    with open(filename, "r", encoding="utf-8") as csv_file:
        # TODO: maybe change this one to accomadate for multiple files

        g = Graph()

        csv_reader = csv.reader(csv_file)
        with open("relations_mapping.json", "r") as mapper:
            ontology_dict_list = json.load(mapper)

        header = next(csv_reader)

        # Convert each row to Turtle format and add it to the output
        # TODO: Recursive approach would be O(n)?, nested loop is O(n^2). Can it be optimized?
        for row in csv_reader:
            # the key is defined in the mapper
            for ontology_dict in ontology_dict_list:
                key_attr = ontology_dict["key"]
                subject = URIRef(row[header.index(key_attr)])
                if "type" in ontology_dict:
                    g.add((subject, RDF.type, URIRef(ontology_dict["type"])))
                else:
                    raise ValueError("No type specifications in the mapper file.")

                # extracting other informations
                # TODO: is the source description texts needed?
                for i, element in enumerate(row[1:]):
                    predicate_cur = header[i + 1]
                    # finding the predicate from csv in the config dictionary, if not exit, skip
                    if predicate_cur not in ontology_dict or predicate_cur == key_attr:
                        continue

                    predicate = URIRef(ontology_dict[predicate_cur])

                    # the object might be an URI or a literal
                    if validators.url(element):
                        obj = URIRef(element)
                    else:
                        obj = Literal(element)

                    g.add((subject, predicate, obj))

    return g


# openrefine_csv_test.csv
# is generated by openrefine and used for testing
# Convert the CSV data to Turtle format
if __name__ == "__main__":
    turtle_data = convert_csv_to_turtle(sys.argv[1])
    turtle_data.serialize(format="turtle", destination="test.ttl")
