import csv
import validators
import sys
import json
import os
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDF
from typing import Optional

DIRNAME = os.path.dirname(__file__)
mapping_filename = os.path.join(DIRNAME, 'relations_mapping_mb.json')
dest_filename = os.path.join(DIRNAME, 'out_rdf.ttl')

def convert_csv_to_turtle(filename) -> Graph:
    """
    (str) -> Graph

    Adds all informations as RDF triples from the input filename into a graph and return it.
    *Important: This input file must have the first column as subjects of all triples
    
    @Pre: type(filename) == str
    """
    with open(filename, "r", encoding="utf-8") as csv_file:
        # TODO: maybe change this one to accomadate for multiple files

        g = Graph()

        csv_reader = csv.reader(csv_file)
        ontology_dict = json.load(open(mapping_filename, "r"))

        header = next(csv_reader)
        header_without_subject = header[1:]
        predicates = []
        for column in header_without_subject:
            if column in ontology_dict:
                predicates.append(URIRef(ontology_dict[column]))

        try:
            ontology_type: Optional[str] = ontology_dict["type"]
        except KeyError:
            ontology_type = None

        # Convert each row to Turtle format and add it to the output
        for row in csv_reader:
            # the first column as the subject
            key_attribute = URIRef(row[0])
            if ontology_type:
                g.add((key_attribute, RDF.type, URIRef(ontology_type)))

            # extracting other informations
            for i, element in enumerate(row[1:]):
                if element == "":
                    continue

                # the object might be an URI or a literal
                if validators.url(element):
                    obj = URIRef(element)
                else:
                    obj = Literal(element)

                g.add((key_attribute, predicates[i], obj))

    return g


# Run this file in the command line.
# Arg 1 = the input reconciled csv using openrefine
# An example in this directory: openrefine_csv_test.csv
# is generated by openrefine and used for testing
# Convert the CSV data to Turtle format
# out_rdf.ttl can be safely imported into Virtuoso.
if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise ValueError("Invalid number of input filename")

    turtle_data = convert_csv_to_turtle(sys.argv[1])
    turtle_data.serialize(format="turtle", destination=dest_filename)
