# Retrieve all persons with RISM ID from Wikidata. The result can be added to people.csv file in the same folder.
SELECT ?person ?rism
WHERE {
  ?person wdt:P5504 ?rismID ; # wdt:P5504 is RISM ID
          wdt:P31 wd:Q5 . # wdt:P31 is instance of; wd:Q5 is human
  BIND(URI(CONCAT("https://rism.online/", ?rismID)) AS ?rism) # assemble the URI of RISM for the person
}

# Retrieve all institutions with RISM ID from Wikidata. The result can be added to institutions.csv file in the same folder.
SELECT ?institution ?rism
WHERE {
  ?institution wdt:P5504 ?rismID . # wdt:P5504 is RISM ID
  FILTER NOT EXISTS { ?institution wdt:P31 wd:Q5 } # wdt:P31 is instance of; wd:Q5 is human
  BIND(URI(CONCAT("https://rism.online/", ?rismID)) AS ?rism)
}