[general]
name = ""
csv_folder = "../../data/cantus/reconciled"
rdf_output_folder = ""
test_mode = false

[namespaces]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
xsd = "http://www.w3.org/2001/XMLSchema#"
wd = "http://www.wikidata.org/entity/"
wdt = "http://www.wikidata.org/prop/direct/"

[cantus-reconciled]
PRIMARY_KEY = "chant_id"
chant_id = ""
source_id = ""
shelfmark = ""
holding_institution = ""
marginalia = ""
folio = ""
sequence = ""
incipit = ""
feast = ""
service_original = ""
service = ""
genre_original = ""
genre = ""
position = ""
cantus_id = ""
mode_original = ""
mode = ""
finalis = ""
differentia = ""
differentiae_database = ""
fulltext_standardized = ""
fulltext_ms = ""
volpiano = ""
image_link = ""
melody_id = ""
addendum = ""
extra = ""
