[general]
name = "thesession"
csv_folder = "../../data/thesession/reconciled"
rdf_output_path = "../thesession/"

[namespaces]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
xs = "http://www.w3.org/2001/XMLSchema"
wd = "http://www.wikidata.org/entity/"
wdt = "http://www.wikidata.org/prop/direct/"
skos = "http://www.w3.org/2004/02/skos/core#"

[events-reconciled]
PRIMARY_KEY = "events_id"
events_id = ""
event = "rdfs:label"
venue = ""
venue_literal = "P276"  # location(P276)
venue_wiki = "P276"  # location(P276)
town = "P276"  # location(P276)
town_literal = ""
town_wiki = ""
area_literal = ""
area_wiki = ""
country = "P17"  # country(P17)
country_literal = ""
country_wiki = ""
latitude = ""
longitude = ""

[events-reconciled.dtstart]
pred = "P580"  # start time(P580)
datatype = "xsd:dateTime"

[events-reconciled.dtend]
pred = "P582"  # end time(P582)
datatype = "xsd:dateTime"

[events-reconciled.address]
pred = "P6375"  # street address(P6375)
subj = "venue"

[events-reconciled.area]
pred = "P276"  # location(P276)
subj = "town"

[events-reconciled.coordinate]
pred = "P625"  # coordinate location(P625)
datatype = "geo:wktLiteral"

[recordings-reconciled]
PRIMARY_KEY = "recording_id"
recording_id = ""
artist = "P170"  # creator(P170)
artist_literal = ""
recording = "rdfs:label"
recording_literal = ""
recording_wiki = ""
track = ""
number = ""
tune = "rdfs:label"
tune_id = "P361"  # part of(P361)
artist_url = ""

[sessions-reconciled]
PRIMARY_KEY = "sessions_id"
sessions_id = ""
name = "P276"  # location(P276)
area = ""
area_wiki = ""
country_wiki = ""
latitude = ""
longitude = ""

[sessions-reconciled.address]
pred = "P6375"  # street address(P6375)
subj = "name"

[sessions-reconciled.town]
pred = "P131"  # located in the administrative territorial entity(P131)
subj = "name"

[sessions-reconciled.country]
pred = "P17"  # country(P17)
subj = "name"

[sessions-reconciled.coordinate]
pred = "P625"  # coordinate location(P625)
datatype = "geo:wktLiteral"

[sessions-reconciled.date]
pred = "P585"  # point in time(P585)
datatype = "xsd:dateTime"

[sets-reconciled]
PRIMARY_KEY = "tuneset_id"
tuneset_id = ""
date = ""
member_id = ""
username = ""
settingorder = ""
name = ""
tune_id = ""
setting_id = ""

[tune-aliases-reconciled]
PRIMARY_KEY = "tune_id"
tune_id = ""
alias = "skos:altLabel"
name = ""

[tune-popularity-reconciled]
PRIMARY_KEY = "tune_id"
tune_id = ""
name = ""
tunebooks = ""

[tunes-reconciled]
PRIMARY_KEY = "tune_id"
tune_id = ""
setting_id = "P747"
type = "P7937"
type_wiki = ""
meter = "P3400"
meter_wiki = ""
mode = "P826"
mode_wiki = ""
username = ""

[tunes-reconciled.name]
pred = "rdfs:label"
subj = "setting_id"

[tunes-reconciled.date]
pred = "P585"
datatype = "xsd:dateTime"

